###

POST http://localhost:8080/cartDetail
Accept: application/json
Content-Type: application/json

{
  "qtty": 4,
  "cartId": 1,
  "productId": 1

}

###
GET http://localhost:8080/cartDetail
Accept: application/json
###

GET http://localhost:8080/cart
Accept: application/json
###

POST http://localhost:8080/cart
Accept: application/json

###

DELETE http://localhost:8080/cartDetail/12
Accept: application/json
Content-Type: application/json

{
  "cartDetailId": 12
}

###