
POST http://localhost:8080/products
Accept: application/json
Content-Type: application/json

{
  "productName": "Laptop Alienware",
  "detail": "procesador i7 9700k",
  "model": "M 17",
  "price": 15500.5,
  "stock": 15,
  "description": "Laptop gamer de 17 pulgadas",
  "storeAvailable": true,
  "deliveryAvailable": true,
  "image": "imagenDell",
  "brand": "Alienware",
  "category": 4

}

###

PATCH http://localhost:8080/products/1
Accept: application/json
Content-Type: application/json

{

"price": 12511.5,
"stock": 100
}

###

DELETE http://localhost:8080/products/1
Accept: application/json
Content-Type: application/json

{
"txStatus": 0
}


###
GET http://localhost:8080/products/1
Accept: application/json

###