
POST http://localhost:8080/products
Accept: application/json
Content-Type: application/json

{
"brand": "Alienware",
"model": "Area 51",
"price": 15500.5,
"description": "Laptop gamer de 15,3 pulgadas",
"stock": 15
}

###

PATCH http://localhost:8080/products/1
Accept: application/json
Content-Type: application/json

{

"price": 12511.5,
"stock": 100
}

###

DELETE http://localhost:8080/products/1
Accept: application/json
Content-Type: application/json

{
"txStatus": 1
}


###
