
POST http://localhost:8080/users/signup
Accept: application/json
Content-Type: application/json

{
  "firstname": "Juan",
  "lastname": "Camacho",
  "phone": "+59178945098",
  "email": "jperez@mail.com",
  "password": "hello_there",
  "neighbourId": 1,
  "street": "Av. Busch",
  "number": "123-A",
  "reference": "Entrando media cuadra de Av. Busch"
}

###

PATCH http://localhost:8080/users/edit/1
Accept: application/json
Content-Type: application/json

{
  "firstname": "Juan",
  "lastname": "Fernandez",
  "phone": "+59171232678",
  "neighbour": "Obrajes",
  "street": "Av. 14 de Septiembre",
  "number": "123-B",
  "reference": "Entrando media cuadra"
}

###

GET http://localhost:8080/users/1
Accept: application/json

###

GET http://localhost:8080/users/orders/1

###