
POST http://localhost:8080/users/signup
Accept: application/json
Content-Type: application/json

{
  "firstname": "Juan",
  "lastname": "Perez",
  "phone": "+59178945098",
  "email": "jperez@mail.com",
  "password": "hello_there",
  "neighbour": "Miraflores",
  "street": "Av. Busch",
  "number": "123-A",
  "reference": "Entrando media cuadra de Av. Busch"
}

###

PATCH http://localhost:8080/users/edit/
Accept: application/json
Content-Type: application/json

{
  "firstname": "Pedro",
  "lastname": "Perez",
  "phone": "+59171232678",
  "neighbour": "Alto Obrajes",
  "street": "Av. Del mAESTRO",
  "number": "123-B",
  "reference": "Entrando media cuadra"
}